# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e78af88c8713f7ee397a070d4c02e40f3572466596b279d07778f74fa15a4622d5edbb5bffe6c48c23430691c765caca4e8c9eb157756a231b72e74cbcf2e95f

test:
  secret_key_base: 16c261e511d51020d0068ff26afa529b8d6d8ae4eaa266cc819ff578f1ccac569f59be0de9e70cf8eb81ac7fef61181939d6b40be0e30c6fdc95358a6a85a20f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
